version: '3'
services:
  web:
    image: hellodk/static-web-app:latest
    ports:
      - 80:80
    volumes:
      - data-volume:/var/log/nginx
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=mongoadmin
      - MONGODB_DATABASE=access
    ports:
      - 27017
    volumes:
      - mongo-volume:/var/lib/mongo
    links:
      - web
  shipper:
    image: fluent/fluentd:latest
    volumes:
      - data-volume:/var/log/nginx
volumes:
  data-volume: {}
  mongo-volume: {}
